
# --- FONTS ----
defaultFont = 20 "Inter Bold"
@foreground=#FFFFFF

# --- COMPONENT STYLES ---
# Text Fields
TextField.background = #FFFFFF
TextField.foreground = #000000
PasswordField.background = #FFFFFF
PasswordField.foreground = #000000
TextField.borderColor = #CCCCCC
TextField.focusedBorderColor = #FF9800

# Buttons
Button.innerFocusWidth = 0

# Button gradient
Button.background = #FF4B2B
Button.focusedBackground = darken(#FF4B2B, 10%)
Button.paintDesign = true
@gradientStart = #FF4B2B
@gradientEnd = #FFAD06

JOptionPane.background = #F11111
